In [31]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series

In [2]:
word_tag_df = pd.read_csv("POS.train", sep = '\t', header = None)

In [3]:
with open("POS.train", "r") as file:
    text =  file.read()

In [4]:
text = text.split()

In [57]:
word_tag_df_old = DataFrame (text)
# extracting the word and the tag in different columns
word_tag_df_old = word_tag_df_old[word_tag_df_old.columns[0]].str.rsplit("/", n = 1, expand = True)
word_tag_df_old.columns = ['Words', 'Tags']
# tags before splitting
tags_df = word_tag_df_old.Tags
tags_df
tags_column_df = word_tag_df_old.filter(['Tags'], axis = 1)
# word_tag_df_old
tags_column_df
    
#     idxs = np.array_split(tags_column_df.index, idx+1)
#     new_df = pd.DataFrame([['.']], columns=tags_column_df.columns)
#     new_df.index += idxs[1].min()
#     tags_column_df = tags_column_df.set_index(idxs[0].union(idxs[1]+len(new_df)))
#     tags_column_df = tags_column_df.append(new_df)
#     tags_column_df.sort_index(inplace=True)
#     new_df
#     tags_column_df.set_index(idxs[0].union(idxs[1] + 1), inplace=True)
#     tags_column_df.loc[idx+1] = ["."]
#     tags_column_df.sort_index(inplace=True)

       Tags
0        NP
1        NP
2         ,
3        CD
4       NNS
...     ...
242256   JJ
242257   NN
242258   IN
242259   NN
242260    .

[242261 rows x 1 columns]

In [73]:
list_of_EOS = tags_column_df.index[tags_df == "."].to_list()
# for idx in list_of_EOS:
dfs = np.split(tags_column_df, [18])
pd.concat([dfs[0], pd.DataFrame([["SRT"]], columns=tags_column_df.columns), dfs[1]], ignore_index=True, axis= 0)

       Tags
0        NP
1        NP
2         ,
3        CD
4       NNS
...     ...
242257   JJ
242258   NN
242259   IN
242260   NN
242261    .

[242262 rows x 1 columns]

In [74]:
tags_column_df.head(20)

   Tags
0    NP
1    NP
2     ,
3    CD
4   NNS
5    JJ
6     ,
7    MD
8    VB
9    DT
10   NN
11   IN
12   DT
13   JJ
14   NN
15   NP
16   CD
17    .
18   NP
19   NP

In [6]:
# creating a list of sentences
words_list = tags_list = word_tag_df_old['Words'].to_list()
sentence_list = []
sentence = ""
for word in words_list:
    if word != ".":
        sentence += word + " "
    else: 
        sentence = sentence[:-1] + "."
        sentence_list.append(sentence)
        sentence = ""
# sentence_list

In [7]:
# to seperate tokens for words with multiple tokens
word_tag_df = word_tag_df_old.copy()
s = word_tag_df['Tags'].str.split('|').apply(Series, 1).stack()
s.index = s.index.droplevel(-1)
s.name = 'Tags'
del word_tag_df['Tags']
word_tag_df = word_tag_df.join(s)
# word_tag_df

In [8]:
# distinct tag-count dictionary
unique_tags_dict = word_tag_df.Tags.value_counts()
unique_tags_dict = unique_tags_dict.to_dict()
# unique_tags_dict

In [9]:
# creating a word-tag dictionary
word_tag_list = list(word_tag_df.to_records(index=False))        
word_tag_dict = {}
for x in word_tag_list:
#     print(x)
    if x[0] not in word_tag_dict.keys():
        word_tag_dict[x[0]] ={}
        if x[1] not in word_tag_dict[x[0]].keys():
            word_tag_dict[x[0]][x[1]] = 1
        else:
            word_tag_dict[x[0]][x[1]] += 1
    else:
        if x[1] not in word_tag_dict[x[0]].keys():
            word_tag_dict[x[0]][x[1]] = 1
        else:
            word_tag_dict[x[0]][x[1]] += 1
        
word_tag_dict['about']["IN"]

338

In [10]:
# finding probabilites
word_tag_prob = {}
for word, tag_dict in word_tag_dict.items():
    for tag in tag_dict.keys():
        probablity = float(word_tag_dict[word][tag]/unique_tags_dict[tag])
        word_tag_prob[word] = {tag: probablity} 
# word_tag_prob

In [11]:
def adding_tag1_tag2_to_dict(tag, prev_tag, tag_dict):
    if tag not in tags_pair_dict.keys():
        tags_pair_dict[tag] = {prev_tag: [1]}
    else:
        if tags_list[i-1] not in tags_pair_dict[tag].keys():
            tags_pair_dict[tag] = {prev_tag: [1]}
        else:
            tags_pair_dict[tag][prev_tag][0] += 1

In [12]:
# creating token-pair dictionary
starting_tag = "SRT"
tags_list = word_tag_df_old['Tags'].to_list()
tags_pair_dict = {}
for i in range(len(tags_list)):
    if i == 0:
        tags_pair_dict[starting_tag] = {tags_list[0]: [1]}
    else:
        tag2 = tags_list[i]
        tag1 = tags_list[i-1]
        if ((tag1.find('|') != -1) and (tag2.find('|') != -1)):
            for t2_element in tag2.split('|'):
                for t1_element in tag1.split('|'):
                    adding_tag1_tag2_to_dict(t2_element, t1_element, tags_pair_dict)
            
        elif tag1.find('|') != -1:
            for t1_element in tag1.split('|'):
                adding_tag1_tag2_to_dict(tag2, t1_element, tags_pair_dict)
                
        elif tag2.find('|') != -1:
            for t2_element in tag2.split('|'):
                adding_tag1_tag2_to_dict(t2_element, tag1, tags_pair_dict)
        else:
            adding_tag1_tag2_to_dict(tag2, tag1, tags_pair_dict)
            
# tags_pair_dict
# tags_list

In [13]:
# tag-tag probabilties 
for tag2 in tags_pair_dict.keys():
    for tag1 in tags_pair_dict[tag2].keys():
        prob = tags_pair_dict[tag2][tag1][0]/unique_tags_dict[tag1]
        tags_pair_dict[tag2][tag1].append(prob)
# tags_pair_dict

In [ ]:
# implementing the veterbi algorithm

for sentence in text_sentences: